fix wasm location
rustwasm/rust_wasm_template pull request #7
Opened 2018-06-08 21:08 UTC by xtuc

Sorry my last PR broke the build script:

```
================================================================================
Final `.wasm` Size
--------------------------------------------------------------------------------

wc: 'hello.wasm'$'\n''rust_wasm_template_bg.wasm': No such file or directory
```

Here's a fix.

2018-06-08 22:56 UTC, fitzgen commented
@xtuc still getting errors: https://travis-ci.org/rustwasm/rust_wasm_template/jobs/389918134#L592-L598

```
ls: cannot access dist/*.wasm: No such file or directory
================================================================================
Final `.wasm` Size
--------------------------------------------------------------------------------
wc: invalid zero-length file name
```

2018-06-09 10:23 UTC, sendilkumarn requested changes

2018-06-09 10:23 UTC, sendilkumarn commented on ci/script.sh
> +    local local_wasm_file=$(ls dist/*.wasm)
This should not be dist, since you are just passing the same directory in line # 115

2018-06-09 13:13 UTC, xtuc commented on ci/script.sh
> +    local local_wasm_file=$(ls dist/*.wasm)
Actually I need the binary emited by webpack which is in dist. The issue is that i'm not calling webpack before here

2018-06-09 15:43 UTC, sendilkumarn approved these changes

2018-06-11 22:40 UTC, merged